### ISSUE TITLE
Optimize memory usage

### ISSUE THREAD

**Issue by maggch97** [maggch97/Frame-Sync#4]
Currently, extension uses a fixed frame buffer size 300. 300 is a too big number if the audio latency is lower than 2 seconds. The buffer will use more than 5 GB memeory if wathing 4k youtube video. So the high priority thing is to make the buffer size dynamic change.

**Comment by huszarrichard** [comment]
Same here

**Comment by maggch97** [comment]
> Same here

I have submitted a new version 1.4 and it should be available in store in a few hous.
It only uses extra 500MB memory when wathing 4K youtube video with 350ms delay.

**Comment by maggch97** [comment]
If set the delay to 2s, about 2.5GB memory will be used. It's not good, but better than before.

**Comment by maggch97** [comment]
1.4 is in store now.

**Comment by Piedone** [comment]
Just wanted to say, awesome stuff, thank you for creating this extension!
