### ISSUE TITLE
Toggle button on extension's popup

### ISSUE THREAD

**Issue by WillTrem** [maggch97/Frame-Sync#7]
The extension works great for my bluetooth earbuds!

However, since I'm also using a pair of wired headphones which don't need the added video delay, I thought it would be nice to have a toggle button on the extension's popup. 

I feel it would be more convenient than deleting the delay number and re-setting it every time I switch headphones.

Cheers!

**Comment by maggch97** [comment]
Thanks, this suggestion is really good. I will update the extension tomorrow.

**Comment by maggch97** [comment]
Version 1.5 is in store

**Comment by WillTrem** [comment]
That's awesome, thank you! :)
